<?php

namespace ContainerJqmo69V;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeletedatasControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DeletedatasController' shared autowired service.
     *
     * @return \App\Controller\DeletedatasController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DeletedatasController'] = $instance = new \App\Controller\DeletedatasController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\PromoRepository'] ?? $container->load('getPromoRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.0QcI221'] ?? $container->load('get_ServiceLocator_0QcI221Service'))->withContext('App\\Controller\\DeletedatasController', $container));

        return $instance;
    }
}
