<?php

namespace ContainerJqmo69V;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PromoController' shared autowired service.
     *
     * @return \App\Controller\PromoController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PromoController'] = $instance = new \App\Controller\PromoController(($container->privates['App\\Repository\\PromoRepository'] ?? $container->load('getPromoRepositoryService')), ($container->services['session'] ?? $container->getSessionService()));

        $instance->setContainer(($container->privates['.service_locator.0QcI221'] ?? $container->load('get_ServiceLocator_0QcI221Service'))->withContext('App\\Controller\\PromoController', $container));

        return $instance;
    }
}
