<?php

namespace Container6IbJ8A9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PromoRepository' shared autowired service.
     *
     * @return \App\Repository\PromoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PromoRepository'] = new \App\Repository\PromoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
