<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5kcngRn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5kcngRn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5kcngRn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5kcngRn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5kcngRn\App_KernelDevDebugContainer([
    'container.build_hash' => '5kcngRn',
    'container.build_id' => '59b84d16',
    'container.build_time' => 1706226452,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5kcngRn');
